"""add invoice_pdfs: the frozen PDF of an issued invoice, with its protection triggers

Revision ID: a85e1c4d7f90
Revises: f74d0b3c9e56
Create Date: 2026-10-03 23:40:24.332955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85e1c4d7f90'
down_revision: Union[str, Sequence[str], None] = 'f74d0b3c9e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_pdfs',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('renderer', sa.String(length=255), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sha256 = encode(sha256(content), 'hex')", name='ck_invoice_pdfs_sha256_matches'),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$' AND source_sha256 ~ '^[0-9a-f]{64}$'", name='ck_invoice_pdfs_hash_shape'),
    sa.CheckConstraint("substring(content from 1 for 5) = decode('255044462d', 'hex')", name='ck_invoice_pdfs_is_pdf'),
    sa.CheckConstraint("template_version >= 1 AND renderer <> ''", name='ck_invoice_pdfs_provenance'),
    sa.CheckConstraint('byte_size > 0 AND byte_size = octet_length(content)', name='ck_invoice_pdfs_byte_size'),
    sa.ForeignKeyConstraint(['organization_id', 'invoice_id'], ['invoices.organization_id', 'invoices.id'], name='fk_invoice_pdfs_invoice_same_organization', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'invoice_id', name='uq_invoice_pdfs_one_per_invoice')
    )
    op.create_index(op.f('ix_invoice_pdfs_organization_id'), 'invoice_pdfs', ['organization_id'], unique=False)
    # ### end Alembic commands ###

    # A frozen artifact never changes and is never removed; only an issued invoice can receive one.
    # (Invoice-local: this function reads only the invoices table.)
    op.execute(
        """
        CREATE FUNCTION invoice_pdfs_guard() RETURNS trigger AS $$
        DECLARE
            current_status text;
        BEGIN
            IF TG_OP = 'INSERT' THEN
                SELECT status INTO current_status FROM invoices
                    WHERE organization_id = NEW.organization_id AND id = NEW.invoice_id;
                IF current_status IS DISTINCT FROM 'issued' THEN
                    RAISE EXCEPTION 'only an issued invoice can have a PDF' USING ERRCODE = 'check_violation';
                END IF;
                RETURN NEW;
            END IF;
            RAISE EXCEPTION 'a frozen invoice PDF cannot be changed or deleted' USING ERRCODE = 'check_violation';
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_invoice_pdfs_guard
        BEFORE INSERT OR UPDATE OR DELETE ON invoice_pdfs
        FOR EACH ROW EXECUTE FUNCTION invoice_pdfs_guard()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER trg_invoice_pdfs_guard ON invoice_pdfs")
    op.execute("DROP FUNCTION invoice_pdfs_guard()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_pdfs_organization_id'), table_name='invoice_pdfs')
    op.drop_table('invoice_pdfs')
    # ### end Alembic commands ###
