"""add authentication: credentials, sessions, setup tokens, security events

Revision ID: b96f2d4e8a13
Revises: a85e1c4d7f90
Create Date: 2026-10-04 15:05:45.349480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96f2d4e8a13'
down_revision: Union[str, Sequence[str], None] = 'a85e1c4d7f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.CheckConstraint("revoked_reason IS NULL OR revoked_reason IN ('logout', 'rotated', 'password_changed', 'cap', 'disabled', 'setup')", name='ck_auth_sessions_revoked_reason'),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$' AND csrf_hash ~ '^[0-9a-f]{64}$'", name='ck_auth_sessions_hash_shape'),
    sa.CheckConstraint('(revoked_at IS NULL) = (revoked_reason IS NULL)', name='ck_auth_sessions_revocation_pair'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_auth_sessions_absolute_expires_at', 'auth_sessions', ['absolute_expires_at'], unique=False)
    op.create_index('ix_auth_sessions_user_active', 'auth_sessions', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('security_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('identifier_hash', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.String(length=64), nullable=True),
    sa.CheckConstraint("event_type IN ('login_success', 'login_failure', 'logout', 'password_changed', 'password_change_failure', 'setup_link_issued', 'setup_redeemed', 'setup_failure', 'user_disabled', 'user_enabled')", name='ck_security_events_type'),
    sa.CheckConstraint("identifier_hash IS NULL OR identifier_hash ~ '^[0-9a-f]{64}$'", name='ck_security_events_identifier_shape'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_occurred_at', 'security_events', ['occurred_at'], unique=False)
    op.create_index('ix_security_events_type_identifier_time', 'security_events', ['event_type', 'identifier_hash', 'occurred_at'], unique=False)
    op.create_index('ix_security_events_type_source_time', 'security_events', ['event_type', 'source', 'occurred_at'], unique=False)
    op.create_index('ix_security_events_type_time', 'security_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('user_credentials',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("left(password_hash, 10) = '$argon2id$'", name='ck_user_credentials_argon2id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_setup_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("purpose IN ('set_password')", name='ck_user_setup_tokens_purpose'),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name='ck_user_setup_tokens_hash_shape'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_user_setup_tokens_expires_at', 'user_setup_tokens', ['expires_at'], unique=False)
    op.create_index('uq_user_setup_tokens_outstanding', 'user_setup_tokens', ['user_id', 'purpose'], unique=True, postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))
    op.add_column('users', sa.Column('can_create_organizations', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

    # security_events is append-only: no row is ever updated, and a row younger than a day cannot be deleted
    # (purging removes rows older than the configured retention, which is at least a day).
    op.execute(
        """
        CREATE FUNCTION security_events_append_only() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'UPDATE' THEN
                RAISE EXCEPTION 'security events cannot be changed' USING ERRCODE = 'check_violation';
            END IF;
            IF OLD.occurred_at > now() - interval '1 day' THEN
                RAISE EXCEPTION 'security events younger than one day cannot be deleted' USING ERRCODE = 'check_violation';
            END IF;
            RETURN OLD;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_security_events_append_only
        BEFORE UPDATE OR DELETE ON security_events
        FOR EACH ROW EXECUTE FUNCTION security_events_append_only()
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER trg_security_events_append_only ON security_events")
    op.execute("DROP FUNCTION security_events_append_only()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_create_organizations')
    op.drop_index('uq_user_setup_tokens_outstanding', table_name='user_setup_tokens', postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))
    op.drop_index('ix_user_setup_tokens_expires_at', table_name='user_setup_tokens')
    op.drop_table('user_setup_tokens')
    op.drop_table('user_credentials')
    op.drop_index('ix_security_events_type_time', table_name='security_events')
    op.drop_index('ix_security_events_type_source_time', table_name='security_events')
    op.drop_index('ix_security_events_type_identifier_time', table_name='security_events')
    op.drop_index('ix_security_events_occurred_at', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index('ix_auth_sessions_user_active', table_name='auth_sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_auth_sessions_absolute_expires_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
