"""add organization creation requests and organization ids on security events

Revision ID: c07a3e5f9b24
Revises: b96f2d4e8a13
Create Date: 2026-10-04 19:16:58.324524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c07a3e5f9b24'
down_revision: Union[str, Sequence[str], None] = 'b96f2d4e8a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_creation_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('request_key', sa.String(length=43), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("request_hash ~ '^[0-9a-f]{64}$'", name='ck_organization_creation_requests_hash_shape'),
    sa.CheckConstraint("request_key ~ '^[A-Za-z0-9_-]{43}$'", name='ck_organization_creation_requests_key_shape'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id', 'request_key'),
    sa.UniqueConstraint('organization_id')
    )
    op.add_column('security_events', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('ix_security_events_organization_time', 'security_events', ['organization_id', 'occurred_at'], unique=False, postgresql_where=sa.text('organization_id IS NOT NULL'))
    # ### end Alembic commands ###

    # Two new kinds of security event. (Alembic does not detect a changed CHECK, so it is replaced by hand.)
    op.drop_constraint("ck_security_events_type", "security_events", type_="check")
    op.create_check_constraint("ck_security_events_type", "security_events", "event_type IN ('login_success', 'login_failure', 'logout', 'password_changed', 'password_change_failure', 'setup_link_issued', 'setup_redeemed', 'setup_failure', 'user_disabled', 'user_enabled', 'organization_created', 'capability_changed')")


def downgrade() -> None:
    """Downgrade schema."""
    # The events of the two new kinds are removed first (the append-only trigger is lifted for this one statement).
    op.execute("ALTER TABLE security_events DISABLE TRIGGER trg_security_events_append_only")
    op.execute("DELETE FROM security_events WHERE event_type IN ('organization_created', 'capability_changed')")
    op.execute("ALTER TABLE security_events ENABLE TRIGGER trg_security_events_append_only")
    op.drop_constraint("ck_security_events_type", "security_events", type_="check")
    op.create_check_constraint("ck_security_events_type", "security_events", "event_type IN ('login_success', 'login_failure', 'logout', 'password_changed', 'password_change_failure', 'setup_link_issued', 'setup_redeemed', 'setup_failure', 'user_disabled', 'user_enabled')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_events_organization_time', table_name='security_events', postgresql_where=sa.text('organization_id IS NOT NULL'))
    op.drop_column('security_events', 'organization_id')
    op.drop_table('organization_creation_requests')
    # ### end Alembic commands ###
