"""add organization invitations

Revision ID: e29c5d7a3b48
Revises: d18b4c6e2f31
Create Date: 2026-10-04 22:35:24.652577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29c5d7a3b48'
down_revision: Union[str, Sequence[str], None] = 'd18b4c6e2f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email = lower(btrim(email)) AND email <> ''", name='ck_organization_invitations_email_normalized'),
    sa.CheckConstraint("role IN ('owner', 'admin', 'accountant', 'employee', 'viewer')", name='ck_organization_invitations_role'),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name='ck_organization_invitations_token_hash_shape'),
    sa.CheckConstraint('(accepted_at IS NULL) = (accepted_by IS NULL)', name='ck_organization_invitations_accepted_pair'),
    sa.CheckConstraint('NOT (revoked_at IS NOT NULL AND accepted_at IS NOT NULL)', name='ck_organization_invitations_one_outcome'),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index('uq_organization_invitations_pending', 'organization_invitations', ['organization_id', 'email'], unique=True, postgresql_where=sa.text('revoked_at IS NULL AND accepted_at IS NULL'))
    op.create_index('uq_organization_invitations_token_hash', 'organization_invitations', ['token_hash'], unique=True)
    # ### end Alembic commands ###

    # Alembic does not detect a changed CHECK, so it is replaced by hand: three new kinds of security event.
    op.drop_constraint("ck_security_events_type", "security_events", type_="check")
    op.create_check_constraint("ck_security_events_type", "security_events", "event_type IN ('login_success', 'login_failure', 'logout', 'password_changed', 'password_change_failure', 'setup_link_issued', 'setup_redeemed', 'setup_failure', 'user_disabled', 'user_enabled', 'organization_created', 'capability_changed', 'member_role_changed', 'member_removed', 'member_left', 'owner_repaired', 'invitation_created', 'invitation_revoked', 'invitation_accepted')")


def downgrade() -> None:
    """Downgrade schema."""
    # The events of the new kinds are removed first (the append-only trigger is lifted for this one statement).
    op.execute("ALTER TABLE security_events DISABLE TRIGGER trg_security_events_append_only")
    op.execute("DELETE FROM security_events WHERE event_type IN ('invitation_created', 'invitation_revoked', 'invitation_accepted')")
    op.execute("ALTER TABLE security_events ENABLE TRIGGER trg_security_events_append_only")
    op.drop_constraint("ck_security_events_type", "security_events", type_="check")
    op.create_check_constraint("ck_security_events_type", "security_events", "event_type IN ('login_success', 'login_failure', 'logout', 'password_changed', 'password_change_failure', 'setup_link_issued', 'setup_redeemed', 'setup_failure', 'user_disabled', 'user_enabled', 'organization_created', 'capability_changed', 'member_role_changed', 'member_removed', 'member_left', 'owner_repaired')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_organization_invitations_token_hash', table_name='organization_invitations')
    op.drop_index('uq_organization_invitations_pending', table_name='organization_invitations', postgresql_where=sa.text('revoked_at IS NULL AND accepted_at IS NULL'))
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    # ### end Alembic commands ###
