import { expect, test } from "../fixtures";

import { E2E_BFF_SECRET, direct, signInWithPassword } from "../auth-support";
import { BACKEND_URL, BASE_URL } from "../env";
import { FREDRIK, ORG_A, bffUrl } from "../support";

/**
 * D2 end to end, through the real BFF and the real FastAPI (the session run enforces the internal secret on both sides):
 * the internal trust boundary, the health and readiness endpoints, the request id, the security headers, and the coarse
 * failure answers. HSTS is NOT expected here: this run is development over plain http.
 */

test.describe("the BFF -> FastAPI internal secret", () => {
  test("FastAPI refuses every request without the secret (or with a wrong one) before doing anything", async () => {
    for (const path of ["/api/me/user", "/api/me/organizations", "/api/customers", "/openapi.json"]) {
      for (const headers of [{}, { "x-bff-secret": "wrong" }, { "x-bff-secret": E2E_BFF_SECRET.slice(0, -1) }] as Record<string, string>[]) {
        const response = await fetch(`${BACKEND_URL}${path}`, { headers });
        expect(response.status, `${path} ${JSON.stringify(headers)}`).toBe(403);
        expect(response.headers.get("x-internal-auth")).toBe("rejected");
        expect(await response.json()).toEqual({ detail: { code: "internal_auth_failed", message: "Forbidden" } });
      }
    }
    const login = await fetch(`${BACKEND_URL}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: FREDRIK, password: "x" }) });
    expect(login.status).toBe(403); // the pre-auth routes are guarded too: the BFF authenticates itself
  });

  test("FastAPI accepts the secret, and its probes need none", async () => {
    expect((await direct(`${BACKEND_URL}/api/me/user`)).status).toBe(401); // the APPLICATION answered: no user
    expect((await fetch(`${BACKEND_URL}/health`)).status).toBe(200);
    const ready = await fetch(`${BACKEND_URL}/health/ready`);
    expect(ready.status).toBe(200);
    expect(await ready.json()).toEqual({ status: "ready" });
  });

  test("a client address forged in a direct request is not believed without the secret", async () => {
    const response = await fetch(`${BACKEND_URL}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json", "x-client-ip": "203.0.113.99" }, body: JSON.stringify({ email: FREDRIK, password: "x" }) });
    expect(response.status).toBe(403);
  });

  test("the browser cannot supply, replace or learn the secret", async ({ context }) => {
    await signInWithPassword(context, FREDRIK);
    const forged = { "x-bff-secret": "browser-chosen-secret-value-0123456789abcdef", "x-request-id": "browser-chosen-id-0123456789" };
    const response = await context.request.get(bffUrl(ORG_A.id, "/customers?limit=1"), { headers: forged });
    expect(response.status()).toBe(200); // the BFF used ITS OWN secret
    expect(JSON.stringify(response.headers())).not.toContain(E2E_BFF_SECRET);
    expect(await response.text()).not.toContain(E2E_BFF_SECRET);
    expect(response.headers()["x-request-id"]).toMatch(/^[0-9a-f]{32}$/); // generated by the BFF
    expect(response.headers()["x-request-id"]).not.toBe(forged["x-request-id"]);
    for (const path of ["/", "/login", `/o/${ORG_A.id}`]) {
      const page = await context.request.get(path);
      expect(await page.text()).not.toContain(E2E_BFF_SECRET);
    }
  });

  test("the secret is not in any file the browser can download", async ({ page }) => {
    const bodies: string[] = [];
    page.on("response", async (response) => {
      const type = response.headers()["content-type"] ?? "";
      if (/javascript|json|html|css/.test(type)) bodies.push(await response.text().catch(() => ""));
    });
    await page.goto("/login");
    await expect(page.getByTestId("login-form")).toHaveAttribute("data-ready", "true");
    expect(bodies.length).toBeGreaterThan(2);
    expect(bodies.join("\n")).not.toContain(E2E_BFF_SECRET);
  });
});

test.describe("health and readiness", () => {
  test("/api/health is liveness and /api/ready is readiness: both public, coarse and uncached", async ({ request }) => {
    const health = await request.get("/api/health");
    expect(health.status()).toBe(200);
    expect(await health.json()).toEqual({ status: "ok" });
    expect(health.headers()["cache-control"]).toBe("no-store");

    const ready = await request.get("/api/ready");
    expect(ready.status()).toBe(200);
    expect(await ready.json()).toEqual({ status: "ready" });
    expect(ready.headers()["cache-control"]).toBe("no-store");
    const everything = JSON.stringify(ready.headers()) + (await ready.text());
    expect(everything).not.toMatch(/postgres|alembic|revision|127\.0\.0\.1:8002|backend/i);
  });
});

test.describe("security headers", () => {
  const BASELINE = {
    "x-content-type-options": "nosniff",
    "x-frame-options": "DENY",
  };

  test("every kind of response carries the baseline; development over http sends no HSTS", async ({ request }) => {
    for (const path of ["/login", "/", "/api/health", "/no-such-page", "/api/auth/pre"]) {
      const response = await request.get(path, { maxRedirects: 0 });
      const headers = response.headers();
      for (const [name, value] of Object.entries(BASELINE)) expect(headers[name], `${name} on ${path}`).toBe(value);
      expect(headers["permissions-policy"], path).toMatch(/camera=\(\)/);
      expect(headers["strict-transport-security"], `HSTS must not be sent over plain http (${path})`).toBeUndefined();
      expect(headers["x-powered-by"], path).toBeUndefined();
      expect(headers["content-security-policy"], "CSP is tracked separately").toBeUndefined();
    }
  });

  test("the baseline Referrer-Policy is the safe global default", async ({ request }) => {
    expect((await request.get("/api/health")).headers()["referrer-policy"]).toBe("strict-origin-when-cross-origin");
  });

  test("the secret-bearing pages and the authentication API keep the stronger no-referrer and no-store", async ({ request }) => {
    for (const path of ["/login", "/setup", "/invite", "/api/auth/pre"]) {
      const headers = (await request.get(path)).headers();
      expect(headers["referrer-policy"], path).toBe("no-referrer"); // exactly one value: the stronger one won
      expect(headers["cache-control"], path).toBe("no-store");
      expect(headers["x-content-type-options"], path).toBe("nosniff");
    }
  });
});

test.describe("what the browser sees when the page request fails", () => {
  test("a request the BFF refuses is a plain JSON refusal with a request id, not an internal error", async ({ request }) => {
    const response = await request.get(bffUrl(ORG_A.id, "/customers"));
    expect(response.status()).toBe(401);
    expect(response.headers()["x-request-id"]).toMatch(/^[0-9a-f]{32}$/);
    expect(await response.json()).toMatchObject({ detail: "Not authenticated" });
    expect(BASE_URL).toBeTruthy();
  });
});
