import re
import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.models import Role

EMAIL = re.compile(r"^[^\s@]{1,64}@[^\s@]{1,255}\.[^\s@]{1,63}$")


class InvitationCreate(BaseModel):
    """What an administrator provides: who and which role. The organization comes from the URL, the inviter is the
    authenticated user, and the token is generated by the server (none of them is a field here)."""

    model_config = ConfigDict(extra="forbid")

    email: str = Field(max_length=320)
    role: Role

    @field_validator("email")
    @classmethod
    def looks_like_an_email(cls, value: str) -> str:
        value = value.strip()
        if not EMAIL.fullmatch(value):
            raise ValueError("Enter a valid email address")
        return value


class InvitationRead(BaseModel):
    """Never contains the token or its hash."""

    id: uuid.UUID
    email: str
    role: Role
    created_at: datetime
    expires_at: datetime
    state: Literal["pending", "expired"]


class InvitationCreated(InvitationRead):
    """The ONLY response that carries the secret, once. There is no way to read it again."""

    token: str


class TokenBody(BaseModel):
    """The bearer secret travels in a POST body only (never a URL, header or cookie)."""

    model_config = ConfigDict(extra="forbid")

    token: str = Field(max_length=256)


class AcceptNewBody(TokenBody):
    name: str = Field(min_length=1, max_length=255)
    password: str = Field(max_length=4096)

    @field_validator("name")
    @classmethod
    def trimmed(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Enter your name")
        return value


class InvitationPreview(BaseModel):
    organization_name: str
    email: str
    role: Role
    account_exists: bool


class AcceptedResponse(BaseModel):
    organization_id: uuid.UUID
    role: Role
    joined: bool
