import uuid
from datetime import date, datetime
from typing import Annotated

from pydantic import AfterValidator, StringConstraints, field_validator

from app.core.org_time import is_known_zone

from app.schemas.profile import CurrencyCode, ProfileIn, ProfileRead, optional_text

Name = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=255)]
LegalName = optional_text(255)


def _known_zone(value: str) -> str:
    if not is_known_zone(value):
        raise ValueError("must be an IANA time zone name such as Europe/Stockholm")
    return value


# An IANA time zone name, checked against the zone database the backend ships (tzdata).
TimeZoneName = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=64), AfterValidator(_known_zone)]

# There is no organization_id field anywhere: the organization is always the active one.


class OrganizationCreate(ProfileIn):
    """The body of organization creation: what the new tenant is called and the currency it works in.

    There is no owner, user, role or organization id field (and unknown fields are refused): the owner is the
    authenticated user and the id is generated by the server. The currency is REQUIRED and chosen explicitly:
    the platform has no default and does not infer one from a country or locale. The other profile fields stay
    optional here (they are completed later in Settings); nothing about invoicing validation changes.
    """

    name: Name
    default_currency: CurrencyCode
    legal_name: LegalName = None


class OrganizationUpdate(ProfileIn):
    """Partial update of the active organization's settings: only fields present are changed.

    `default_currency` can be set or changed but never cleared (null is refused): an organization
    that has a currency keeps one. Changing a currency that is already set is refused by the
    endpoint once items or transactions exist.
    """

    name: Name | None = None
    legal_name: LegalName = None
    default_currency: CurrencyCode | None = None
    # Null clears it again (dates then default to UTC): nothing stored depends on the zone.
    timezone: TimeZoneName | None = None

    @field_validator("name", "default_currency")
    @classmethod
    def not_null(cls, value):
        # Runs only for fields that were sent.
        if value is None:
            raise ValueError("may not be null")
        return value


class OrganizationRead(ProfileRead):
    id: uuid.UUID
    name: str
    legal_name: str | None
    default_currency: str | None
    # Whether the currency can still be changed, and if not, why (shown next to the field).
    default_currency_locked: bool
    default_currency_lock_reason: str | None
    timezone: str | None
    # The organization's current date in its time zone (UTC when none is set): the default for new dates.
    today: date
    created_at: datetime
    updated_at: datetime
